### ISSUE TITLE
Continuum Protocol Tracking

### ISSUE THREAD

**Issue by justinphamnz** [bit-country/Metaverse-Network#50]
Continuum protocol on Bit.Country helps the community to safeguard and shape the future of the continuum map. 
Auctions slot and EOI rotation logic will be handled on-chain.
Good neighbourhood protocol starts the new round voting process automatically after the top N subscribed Continuum Spots available for Auction.  

- [x] New Round of Continuum Auction Slots will automatically generate every term (24 hours)
- [x] Continuum Spot EOI transition logic - EOI -> New Auction Slots
- [x] Register Continuum EOI
- [x] Governance Set Max Continuum Bound
- [x] Governance Set Max Auction Rate (prevent spam)
- [x] Propose Good Neighborhood Voting
- [x] Voting on GN
- [x] Continuum Auction Bidding
- [x] Continuum Auction Finality
- [x] Unit tests
- [x] More negative test cases

**Comment by justinphamnz** [comment]
#84
